swagger: '2.0'
info:
  title: My API
  description: API description
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@myapi.local
  license:
    name: My License
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /api
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /favorites/cancel-product/:
    delete:
      operationId: favorites_cancel-product_delete
      description: API View to cancel a 'like' for a specific product.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - favorites
    parameters: []
  /favorites/like-product/:
    post:
      operationId: favorites_like-product_create
      description: API View for liking a specific product.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Favorite'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Favorite'
      tags:
      - favorites
    parameters: []
  /favorites/liked/:
    get:
      operationId: favorites_liked_list
      description: API View for retrieving all products that a user has liked.
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Favorite'
      tags:
      - favorites
    parameters: []
  /products/list/:
    get:
      operationId: products_list_list
      description: ''
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Product'
      tags:
      - products
    parameters: []
  /users/login/:
    post:
      operationId: users_login_create
      description: Authenticate a user and return an access token if successful.
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - users
    parameters: []
  /users/register/:
    post:
      operationId: users_register_create
      description: Register a new user.
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - users
    parameters: []
definitions:
  Product:
    required:
    - thumbnail_url
    - origin_price
    - discounted_price
    - status
    - delivery_condition
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      shop_id:
        title: Shop id
        type: integer
        maximum: 9223372036854775807
        minimum: -9223372036854775808
        x-nullable: true
      name:
        title: Name
        type: string
        maxLength: 255
        minLength: 1
        x-nullable: true
      description:
        title: Description
        type: string
        minLength: 1
        x-nullable: true
      thumbnail_url:
        title: Thumbnail url
        type: string
        minLength: 1
      origin_price:
        title: Origin price
        type: integer
        maximum: 9223372036854775807
        minimum: -9223372036854775808
      discounted_price:
        title: Discounted price
        type: integer
        maximum: 9223372036854775807
        minimum: -9223372036854775808
      discounted_rate:
        title: Discounted rate
        type: number
        x-nullable: true
      status:
        title: Status
        type: string
        maxLength: 191
        minLength: 1
      in_stock:
        title: In stock
        type: boolean
      is_preorder:
        title: Is preorder
        type: boolean
      is_purchasable:
        title: Is purchasable
        type: boolean
      delivery_condition:
        title: Delivery condition
        type: string
        maxLength: 255
        minLength: 1
      delivery_display:
        title: Delivery display
        type: string
        minLength: 1
        x-nullable: true
      created_at:
        title: Created at
        type: string
        format: date-time
        readOnly: true
      updated_at:
        title: Updated at
        type: string
        format: date-time
        readOnly: true
  Favorite:
    required:
    - id
    type: object
    properties:
      id:
        title: Id
        type: integer
      product:
        $ref: '#/definitions/Product'
